import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul className="flex text-lg border-b">
            <NavLink name="Lists" href="/lists" />
            <NavLink name="Notes" href="/notes" />
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}

function NavLink({ name, href }: { name: string; href: string }) {
  return (
    <li>
      <Link href={href} className="py-4 px-6 block">
        {name}
      </Link>
    </li>
  );
}
